### ISSUE TITLE
grpc-java application context

### ISSUE THREAD

**Issue by Srumith1** [jyane/context-example#1]
We have an application running on grpc-server in java. We have a requirement to set application-context for this application. Can you please help with some sample code?

Currently, my URL looks like https://host:port/ but we want it to be running on https://host:port/example-server.

Please help !

**Comment by jyane** [comment]
@Srumith1 Would you please explain more clearly? gRPC doesn't support HTTP1, it runs on HTTP2.

**Comment by jyane** [comment]
Closing due to no responses.
